include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gen.dart
    - lib/**/*.config.dart
    - lib/commons/generated/**/*.dart
    - lib/generated/*.dart
    - lib/*.g.dart
    - lib/**/*.arb
  language:
    strict-raw-types: false

linter:
  rules:
    public_member_api_docs: false
    avoid_print: true
    require_trailing_commas: true
    prefer_single_quotes: true
    cascade_invocations: true
    always_use_package_imports: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_string_interpolations: true
    omit_local_variable_types: true
    depend_on_referenced_packages: false
